### ISSUE TITLE
Math exception (when viewing zero-data image?)

### ISSUE THREAD

**Issue by davidraythompson** [openspectra/openspectra#11]
/Users/drt/src/openspectra/openspectra/image.py:198: RuntimeWarning: invalid value encountered in true_divide
  hist_scaled = np.floor((self.__band - min)/(max - min) * (nbins - 1))
/Users/drt/src/anaconda37/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py:3821: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)
Traceback (most recent call last):
  File "/Users/drt/src/openspectra/openspectra/ui/windowmanager.py", line 92, in __handle_rgb_select
    file_set.add_rgb_window_set(bands)
  File "/Users/drt/src/openspectra/openspectra/ui/windowmanager.py", line 117, in add_rgb_window_set
    self.__create_window_set(image)
  File "/Users/drt/src/openspectra/openspectra/ui/windowmanager.py", line 151, in __create_window_set
    window_set.init_position(x, y)
  File "/Users/drt/src/openspectra/openspectra/ui/windowmanager.py", line 391, in init_position
    self.__init_histogram(x, y)
  File "/Users/drt/src/openspectra/openspectra/ui/windowmanager.py", line 247, in __init_histogram
    self.__histogram_tools.adjusted_histogram(Band.GREEN), Band.GREEN)
  File "/Users/drt/src/openspectra/openspectra/ui/plotdisplay.py", line 784, in create_plot_control
    self.__histogram_control.add_plot(raw_data, adjusted_data, band)
  File "/Users/drt/src/openspectra/openspectra/ui/plotdisplay.py", line 725, in add_plot
    plots.set_adjusted_data(adjusted_data)
  File "/Users/drt/src/openspectra/openspectra/ui/plotdisplay.py", line 478, in set_adjusted_data
    self.__adjusted_data_canvas.plot(data)
  File "/Users/drt/src/openspectra/openspectra/ui/plotdisplay.py", line 173, in plot
    color=data.color, linestyle=data.line_style)
  File "/Users/drt/src/anaconda37/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/Users/drt/src/anaconda37/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 6591, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/Users/drt/src/anaconda37/anaconda3/lib/python3.7/site-packages/numpy/lib/histograms.py", line 780, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/Users/drt/src/anaconda37/anaconda3/lib/python3.7/site-packages/numpy/lib/histograms.py", line 415, in _get_bin_edges
    raise ValueError('`bins` must be positive, when an integer')
ValueError: `bins` must be positive, when an integer

**Comment by jconti13** [comment]
Sorry what do you mean by "zero-data image"?
