### ISSUE TITLE
Float division by zero

### ISSUE THREAD

**Issue by davidraythompson** [openspectra/openspectra#4]
On trying to adjust image contrast:

Traceback (most recent call last):
  File "/Users/drt/src/openspectra/openspectra/ui/windowmanager.py", line 354, in __handle_hist_limit_change
    self.__image.adjust()
  File "/Users/drt/src/openspectra/openspectra/image.py", line 447, in adjust
    super().adjust()
  File "/Users/drt/src/openspectra/openspectra/image.py", line 250, in adjust
    self.__adjusted_bands[Band.RED].adjust()
  File "/Users/drt/src/openspectra/openspectra/image.py", line 173, in adjust
    masked_band = ((masked_band - self.__low_cutoff) * ((B - A) / (self.__high_cutoff - self.__low_cutoff)) + A)
ZeroDivisionError: float division by zero
Abort trap: 6

**Comment by jconti13** [comment]
OK I see what's happening here and can reproduce but I'm not sure the best way to resolve it.

I could enforce some sort of minimum separation between the high and low values so they can't be equal.  If that sounds good, what would be a good value?

Or is having those two values equal a valid use case I need to support and if so how should I handle the calculation in this case?
